=== flare-labs-ltd/fasset-bots/run-config/schema/agent-settings.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string"
        },
        "buyFAssetByAgentFactorBIPS": {
            "type": ["string", "number"]
        },
        "feeBIPS": {
            "type": ["string", "number"]
        },
        "mintingPoolCollateralRatioConstant": {
            "type": "number"
        },
        "mintingVaultCollateralRatioConstant": {
            "type": "number"
        },
        "poolExitCollateralRatioConstant": {
            "type": "number"
        },
        "poolFeeShareBIPS": {
            "type": ["string", "number"]
        },
        "poolTopupCollateralRatioConstant": {
            "type": "number"
        },
        "poolTopupTokenPriceFactorBIPS": {
            "type": ["string", "number"]
        },
        "vaultCollateralFtsoSymbol": {
            "type": "string"
        }
    },
    "required": [
        "buyFAssetByAgentFactorBIPS",
        "feeBIPS",
        "mintingPoolCollateralRatioConstant",
        "mintingVaultCollateralRatioConstant",
        "poolExitCollateralRatioConstant",
        "poolFeeShareBIPS",
        "poolTopupCollateralRatioConstant",
        "poolTopupTokenPriceFactorBIPS",
        "vaultCollateralFtsoSymbol"
    ],
    "type": "object"
}

=== flare-labs-ltd/fasset-bots/test-hardhat/test-utils/run-config-tests/agent-settings-config-hardhat.json
{
    "vaultCollateralFtsoSymbol": "USDC",
    "feeBIPS": 1000,
    "poolFeeShareBIPS": 4000,
    "mintingVaultCollateralRatioConstant": 1.2,
    "mintingPoolCollateralRatioConstant": 1.2,
    "poolExitCollateralRatioConstant": 1.3,
    "buyFAssetByAgentFactorBIPS": 9000,
    "poolTopupCollateralRatioConstant": 1.1,
    "poolTopupTokenPriceFactorBIPS": 8000
}
