=== flare-labs-ltd/fasset-bots/run-config/schema/bot-config.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "definitions": {
        "BotFAssetInfo": {
            "additionalProperties": false,
            "properties": {
                "amgDecimals": {
                    "type": "number"
                },
                "assetManager": {
                    "type": "string"
                },
                "chainId": {
                    "type": "string"
                },
                "decimals": {
                    "type": "number"
                },
                "fAssetSymbol": {
                    "type": "string"
                },
                "finalizationBlocks": {
                    "type": "number"
                },
                "inTestnet": {
                    "type": "boolean"
                },
                "indexerUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "priceChangeEmitter": {
                    "type": "string"
                },
                "requireEOAProof": {
                    "type": "boolean"
                },
                "symbol": {
                    "type": "string"
                },
                "walletUrl": {
                    "type": "string"
                }
            },
            "required": ["amgDecimals", "chainId", "decimals", "finalizationBlocks", "name", "requireEOAProof", "symbol"],
            "type": "object"
        },
        "DatabaseType": {
            "enum": ["mysql", "postgresql", "sqlite"],
            "type": "string"
        },
        "NativeChainInfo": {
            "additionalProperties": false,
            "properties": {
                "finalizationBlocks": {
                    "type": "number"
                },
                "readLogsChunkSize": {
                    "type": "number"
                }
            },
            "required": ["finalizationBlocks", "readLogsChunkSize"],
            "type": "object"
        },
        "OrmConfigOptions": {
            "additionalProperties": {},
            "properties": {
                "charset": {
                    "type": "string"
                },
                "clientUrl": {
                    "type": "string"
                },
                "dbName": {
                    "type": "string"
                },
                "debug": {
                    "type": "boolean"
                },
                "host": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "port": {
                    "type": "number"
                },
                "schemaUpdate": {
                    "enum": ["full", "recreate", "safe"],
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/DatabaseType"
                },
                "user": {
                    "type": "string"
                }
            },
            "required": ["type"],
            "type": "object"
        }
    },
    "properties": {
        "$schema": {
            "type": "string"
        },
        "addressUpdater": {
            "type": "string"
        },
        "attestationProviderUrls": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "challengeStrategy": {
            "additionalProperties": false,
            "properties": {
                "className": {
                    "type": "string"
                },
                "config": {}
            },
            "required": ["className"],
            "type": "object"
        },
        "contractsJsonFile": {
            "type": "string"
        },
        "defaultAgentSettingsPath": {
            "type": "string"
        },
        "fAssetInfos": {
            "items": {
                "$ref": "#/definitions/BotFAssetInfo"
            },
            "type": "array"
        },
        "liquidationStrategy": {
            "additionalProperties": false,
            "properties": {
                "className": {
                    "type": "string"
                },
                "config": {}
            },
            "required": ["className"],
            "type": "object"
        },
        "loopDelay": {
            "type": "number"
        },
        "nativeChainInfo": {
            "$ref": "#/definitions/NativeChainInfo"
        },
        "ormOptions": {
            "$ref": "#/definitions/OrmConfigOptions"
        },
        "rpcUrl": {
            "type": "string"
        },
        "stateConnectorAddress": {
            "type": "string"
        },
        "stateConnectorProofVerifierAddress": {
            "type": "string"
        }
    },
    "required": ["fAssetInfos", "loopDelay", "nativeChainInfo", "rpcUrl"],
    "type": "object"
}

=== flare-labs-ltd/fasset-bots/test/test-utils/run-config-test/run-config-coston-with-address-updater.json
{
    "loopDelay": 0,
    "addressUpdater": "0xb006c0cb0b2b8ae48E5B12883Cd5a13654cc6e20",
    "nativeChainInfo": { "finalizationBlocks": 6, "readLogsChunkSize": 10 },
    "fAssetInfos": [
        {
            "chainId": "testXRP",
            "name": "Test XRP",
            "symbol": "testXRP",
            "decimals": 6,
            "amgDecimals": 0,
            "finalizationBlocks": 3,
            "requireEOAProof": false,
            "assetManager": "0x58cCe8be3E84150BBeAb6F56b96Fd4f4Bf4ab7Fc",
            "indexerUrl": "https://attestation-coston.aflabs.net/verifier/xrp",
            "walletUrl": "https://s.altnet.rippletest.net:51234"
        }
    ],
    "ormOptions": {
        "dbName": "fasset-bots-coston.db",
        "debug": false,
        "allowGlobalContext": true,
        "type": "sqlite"
    },
    "rpcUrl": "https://coston-api.flare.network/ext/C/rpc",
    "attestationProviderUrls": ["https://attestation-coston.aflabs.net/attestation-client"],
    "defaultAgentSettingsPath": "./run-config/agent-settings-config.json",
    "stateConnectorProofVerifierAddress": "0x6356470e9aF457d1900Ad4Ed45D115192506BF51"
}

=== flare-labs-ltd/fasset-bots/run-config/run-config-challenger-coston-testxrp.json
{
    "$schema": "./schema/bot-config.schema.json",
    "loopDelay": 5000,
    "contractsJsonFile": "./fasset-deployment/coston.json",
    "nativeChainInfo": { "finalizationBlocks": 6, "readLogsChunkSize": 10 },
    "fAssetInfos": [
        {
            "chainId": "testXRP",
            "name": "Test XRP",
            "symbol": "testXRP",
            "decimals": 6,
            "amgDecimals": 0,
            "finalizationBlocks": 3,
            "requireEOAProof": false,
            "fAssetSymbol": "FtestXRP",
            "indexerUrl": "https://attestation-coston.aflabs.net/verifier/xrp"
        },
        {
            "chainId": "testXRP",
            "name": "Fake XRP",
            "symbol": "fakeXRP",
            "decimals": 6,
            "amgDecimals": 0,
            "finalizationBlocks": 10,
            "requireEOAProof": false,
            "fAssetSymbol": "FfakeXRP",
            "indexerUrl": "https://attestation-coston.aflabs.net/verifier/xrp",
            "priceChangeEmitter": "FakePriceReader"
        }
    ],
    "rpcUrl": "https://coston-api.flare.network/ext/C/rpc",
    "attestationProviderUrls": ["https://attestation-coston.aflabs.net/attestation-client"],
    "challengeStrategy": {
        "className": "DexChallengeStrategy",
        "config": {
            "address": "0xbDcCb53d655f541902De8cf04e68B6E7cE2D9Fa0"
        }
    }
}

=== flare-labs-ltd/fasset-bots/run-config/run-config-liquidator-coston-testxrp.json
{
    "loopDelay": 5000,
    "$schema": "./schema/bot-config.schema.json",
    "contractsJsonFile": "./fasset-deployment/coston.json",
    "nativeChainInfo": { "finalizationBlocks": 6, "readLogsChunkSize": 10 },
    "fAssetInfos": [
        {
            "chainId": "testXRP",
            "name": "Test XRP",
            "symbol": "testXRP",
            "decimals": 6,
            "amgDecimals": 0,
            "finalizationBlocks": 3,
            "requireEOAProof": false,
            "fAssetSymbol": "FtestXRP"
        },
        {
            "chainId": "testXRP",
            "name": "Fake XRP",
            "symbol": "fakeXRP",
            "decimals": 6,
            "amgDecimals": 0,
            "finalizationBlocks": 10,
            "requireEOAProof": false,
            "fAssetSymbol": "FfakeXRP",
            "indexerUrl": "https://attestation-coston.aflabs.net/verifier/xrp",
            "priceChangeEmitter": "FakePriceReader"
        }
    ],
    "rpcUrl": "https://coston-api.flare.network/ext/C/rpc",
    "liquidationStrategy": {
        "className": "DexLiquidationStrategy",
        "config": {
            "address": "0x250D1792DA9aBACEd6b16a47d6aedf4d2cbbaFeb"
        }
    }
}

=== flare-labs-ltd/fasset-bots/run-config/run-config-agent-coston-testxrp.json
{
    "$schema": "./schema/bot-config.schema.json",
    "loopDelay": 5000,
    "contractsJsonFile": "./fasset-deployment/coston.json",
    "nativeChainInfo": {
        "finalizationBlocks": 6,
        "readLogsChunkSize": 10
    },
    "fAssetInfos": [
        {
            "chainId": "testXRP",
            "name": "Test XRP",
            "symbol": "testXRP",
            "decimals": 6,
            "amgDecimals": 0,
            "finalizationBlocks": 3,
            "requireEOAProof": false,
            "fAssetSymbol": "FtestXRP",
            "indexerUrl": "https://attestation-coston.aflabs.net/verifier/xrp",
            "walletUrl": "https://s.altnet.rippletest.net:51234"
        },
        {
            "chainId": "testXRP",
            "name": "Fake XRP",
            "symbol": "fakeXRP",
            "decimals": 6,
            "amgDecimals": 0,
            "finalizationBlocks": 10,
            "requireEOAProof": false,
            "fAssetSymbol": "FfakeXRP",
            "indexerUrl": "https://attestation-coston.aflabs.net/verifier/xrp",
            "walletUrl": "https://s.altnet.rippletest.net:51234",
            "priceChangeEmitter": "FakePriceReader"
        }
    ],
    "ormOptions": {
        "type": "sqlite",
        "dbName": "fasset-bots-coston.db",
        "allowGlobalContext": true
    },
    "rpcUrl": "https://coston-api.flare.network/ext/C/rpc",
    "attestationProviderUrls": ["https://attestation-coston.aflabs.net/attestation-client"],
    "defaultAgentSettingsPath": "./run-config/agent-settings-config.json"
}
