=== flare-labs-ltd/fasset-bots/packages/fasset-bots-core/run-config/schema/agent-settings.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string"
        },
        "buyFAssetByAgentFactor": {
            "description": "FTSO price factor at which the agent pays for burned fassets (in vault tokens) during pool providers' self close exit.",
            "pattern": "^\\d+(\\.\\d+)?%?$",
            "type": "string"
        },
        "fee": {
            "description": "The minting fee percentage.",
            "pattern": "^\\d+(\\.\\d+)?%?$",
            "type": "string"
        },
        "handshakeType": {
            "description": "The handshake type required by the agent. Currently supported values are\n- 0 - no handshake is performed\n- 1 - handshake is performed by external service api (configured further in bot config)",
            "type": "integer"
        },
        "mintingPoolCollateralRatio": {
            "description": "Agent's minting collateral ratio for pool collateral (minimum CR at which the minting can happen).",
            "pattern": "^\\d+(\\.\\d+)?%?$",
            "type": "string"
        },
        "mintingVaultCollateralRatio": {
            "description": "Agent's minting collateral ratio for vault collateral (minimum CR at which the minting can happen).",
            "pattern": "^\\d+(\\.\\d+)?%?$",
            "type": "string"
        },
        "poolExitCollateralRatio": {
            "description": "Collateral pool's exit collateral ratio (minimum CR for pool collateral at which the collateral pool providers can exit;\nhowever, self-close exit is allowed even at lower pool CR).",
            "pattern": "^\\d+(\\.\\d+)?%?$",
            "type": "string"
        },
        "poolFeeShare": {
            "description": "The percentage of the minting fee that goes to the collateral pool.",
            "pattern": "^\\d+(\\.\\d+)?%?$",
            "type": "string"
        },
        "poolTokenSuffix": {
            "description": "Token suffix for the new collateral pool's token.\nMust be unique within this fasset type.",
            "pattern": "^[A-Z0-9](?:[A-Z0-9\\-]{0,18}[A-Z0-9])?$",
            "type": "string"
        },
        "poolTopupCollateralRatio": {
            "description": "Pool collateral ratio below which the providers can enter at discounted rate.",
            "pattern": "^\\d+(\\.\\d+)?%?$",
            "type": "string"
        },
        "poolTopupTokenPriceFactor": {
            "description": "Discounted price factor at which providers can enter when topup is active (i.e. the pool CR is below poolTopupCollateralRatio).",
            "pattern": "^\\d+(\\.\\d+)?%?$",
            "type": "string"
        },
        "vaultCollateralFtsoSymbol": {
            "description": "The tokenFtsoSymbol symbol in the collateral type for the created agent vault vault vollateral.",
            "pattern": "^[\\w\\-]\\w+$",
            "type": "string"
        }
    },
    "required": [
        "buyFAssetByAgentFactor",
        "fee",
        "handshakeType",
        "mintingPoolCollateralRatio",
        "mintingVaultCollateralRatio",
        "poolExitCollateralRatio",
        "poolFeeShare",
        "poolTokenSuffix",
        "poolTopupCollateralRatio",
        "poolTopupTokenPriceFactor",
        "vaultCollateralFtsoSymbol"
    ],
    "type": "object"
}

=== flare-labs-ltd/fasset-bots/packages/fasset-bots-core/test-hardhat/test-utils/run-config-tests/agent-settings-config-hardhat.json
{
    "$schema": "../../../run-config/schema/agent-settings.schema.json",
    "poolTokenSuffix": "ABCX",
    "vaultCollateralFtsoSymbol": "testUSDC",
    "fee": "0.5%",
    "poolFeeShare": "40%",
    "mintingVaultCollateralRatio": "1.6",
    "mintingPoolCollateralRatio": "2.4",
    "poolExitCollateralRatio": "2.6",
    "buyFAssetByAgentFactor": "0.99",
    "poolTopupCollateralRatio": "2.2",
    "poolTopupTokenPriceFactor": "0.8",
    "handshakeType": 0
}
